Integrate API post dataset when edit project. Move get dataset api to useRunPipeline function. Fix bug v.v
arayabrain/MRIAnalysisStudioforMouse pull request #131
Opened 2023-06-07 08:54 UTC by sanglevinh

2023-06-08 02:51 UTC, ReiHashimoto requested changes
各コメントを参照してください。

2023-06-08 02:51 UTC, ReiHashimoto commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +      dispatch(reset())
この処理をgetDataから切り離しているのはどういった意図でしょうか？

2023-06-08 02:51 UTC, ReiHashimoto commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +    getData().then()
then()は必要ですか?

2023-06-08 02:55 UTC, ReiHashimoto commented on frontend/public/lib/js/brainbrowser/volume-viewer/modules/loading.js
> +        // volume.position[axis] = Math.floor(volume.header[axis].space_length / 2)
以下のコメントアウト関連の指摘全般に共通ですが、意図があれば残して良いです。
例えば、仕様の送付を待っているAPIの仕様が判明した際にはコメントアウトを解除する、など。

いずれにせよ、指摘箇所についてはコメントアウトの意図があれば教えてください。またはTODOなどのコメントでわかるようにしてください。

2023-06-08 03:16 UTC, reactplus-thom commented on frontend/public/lib/js/brainbrowser/volume-viewer/modules/loading.js
> +        // volume.position[axis] = Math.floor(volume.header[axis].space_length / 2)
Chỗ này tại sao các bạn lại comment out nhỉ? (ý tôi là nếu ko cần dùng thì xóa đi cũng được nên đang thắc mắc ko biết có lý do gì mà cần comment out không? giả sử nếu mà muốn xem lại code trước đây thì có thể trace bằng git cũng được mà)

Tương tự đối với tất cả những chỗ mà đang comment out dưới đây (mặc dù nếu các bạn có mục đích gì đấy thì cứ giữ lại comment out như thế cũng được. Chẳng hạn các bạn định sẽ xóa comment out khi đã làm rõ về spec của API mà hiện nay chưa có hay sao đó....)

Tóm lại là nhờ các bạn báo lại cho tôi biết lý do tại sao lại comment out như vậy nhé. Hoặc có thể giải thích bằng comment TODO hay gì đó cũng được miễn là làm rõ được lý do.

2023-06-08 03:16 UTC, reactplus-thom commented on frontend/public/lib/js/brainbrowser/volume-viewer/volume-loaders/nifti1.js
> +    // var zmag = magnitude(transform[2])
Chỗ này cũng vậy, ý đồ của các bạn khi comment out là gì?

2023-06-08 03:17 UTC, reactplus-thom commented on frontend/src/pages/Projects/Create.tsx
> +  // editProject,
Ở L42: ý đồ comment out là gì?
Ở L48: lại có dòng code ko được comment out ở L47 là sao?

2023-06-08 03:18 UTC, reactplus-thom commented on frontend/src/store/slice/FlowElement/FlowElementSlice.ts
> +export const initialElements: Elements<NodeData> = [
Tôi nghĩ chỗ này ko cần export cũng được.
Chi tiết sẽ viết ở phía import.

2023-06-08 03:24 UTC, reactplus-thom commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +          filePath: urls,
Ở đây đang import và sử dụng `initialElements` của `frontend/src/store/slice/FlowElement/FlowElementSlice.ts`
tuy nhiên rốt cuộc thì chỉ sử dụng `INITIAL_IMAGE_ELEMENT_ID`  nên tôi đang nghĩ là việc export `initialElements` là không cần thiết.

Thêm nữa, bản thân `initialElements` nó là biến sử dụng cho setting khởi tạo state, nên chúng tôi không muốn nó được tham chiếu từ bên ngoài slice.
Các bạn hãy import và sử dụng trực tiếp `INITIAL_IMAGE_ELEMENT_ID` nhé.

2023-06-08 03:25 UTC, reactplus-thom commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +      dispatch(reset())
Mục đích tách xử lý này khỏi getData là gì?

2023-06-08 03:25 UTC, reactplus-thom commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +    getData().then()
then() liệu có cần thiết không?

2023-06-08 03:42 UTC, sanglevinh commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +    getData().then()
Đây chỉ là cách sử dụng để loại bỏ đi cảnh báo getData là 1 async function trên 1 số IDE. có thể nó không cần thiết nhưng tôi nghĩ để then cũng không gặp vấn đề gì.
@reactplus-thom

2023-06-08 03:45 UTC, sanglevinh commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +      dispatch(reset())
bản thân getData đang là 1 async function nên việc lây giá trị return từ getData là không thể khi useEffect k dùng async.
Có thể code

React.useEffect(async () => {}) nhưng tôi nghĩ cách code này là không nên.
đối với 1 số IDE nó sẽ warning về vấn đề này.
@reactplus-thom

2023-06-08 03:45 UTC, sanglevinh commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +          filePath: urls,
@reactplus-thom @ReiHashimoto  I fixed it.

2023-06-08 03:49 UTC, sanglevinh commented on frontend/public/lib/js/brainbrowser/volume-viewer/modules/loading.js
> +        // volume.position[axis] = Math.floor(volume.header[axis].space_length / 2)
@ReiHashimoto  I have removed it. 
cc: @reactplus-thom

2023-06-08 03:49 UTC, sanglevinh commented on frontend/public/lib/js/brainbrowser/volume-viewer/volume-loaders/nifti1.js
> +    // var zmag = magnitude(transform[2])
@ReiHashimoto I have removed it.
cc: @reactplus-thom

2023-06-08 04:38 UTC, sanglevinh commented on frontend/src/store/slice/FlowElement/FlowElementSlice.ts
> +export const initialElements: Elements<NodeData> = [
@ReiHashimoto  I fixed it.
cc: @reactplus-thom

2023-06-08 04:38 UTC, sanglevinh commented on frontend/src/pages/Projects/Create.tsx
> +  // editProject,
@ReiHashimoto  I added TODO comment
cc: @reactplus-thom

2023-06-08 04:43 UTC, reactplus-thom commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +      dispatch(reset())
@ReiHashimoto 
getData自体はasync関数のため、useEffectでasyncを使用していない場合にgetDataからreturnの値を取得することは不可です。
以下のような実装方法もありますが、
React.useEffect(async () => {}) 

これはよくないと思います。
（一部のIDEでは、これにすると警告が表示されます）

2023-06-08 04:50 UTC, reactplus-thom commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +    getData().then()
@ReiHashimoto 

then()は、一部のIDEで発生する可能性がある、getDataがasync関数であることの警告を避けるために使用しています。
使用する必要はないですが、残しても問題ないかと思います。

2023-06-08 04:54 UTC, ReiHashimoto commented on frontend/src/pages/Projects/Create.tsx
> +  // editProject,
@sanglevinh cc: @reactplus-thom 
I mean, editProject is already imported(at L47).
Therefore, either commenting out(L48-49) or importing is unnecessary.

2023-06-08 05:14 UTC, ReiHashimoto commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +      dispatch(reset())
@sanglevinh 
cc: @reactplus-thom 

OK, I've understood the reason.

However, I think defining asynchronous processing here itself is a problem.

In existing codes, asyncThunk actions are created in XXXAction.ts, 
and updating state with extraReducers in XXXSlice.ts.

Is it difficult to follow these styles?

2023-06-08 06:05 UTC, sanglevinh commented on frontend/src/pages/Projects/Create.tsx
> +  // editProject,
@ReiHashimoto Sorry. I got it. I have removed it.

2023-06-08 06:48 UTC, ReiHashimoto commented
@sanglevinh 
cc: @reactplus-thom 
Thank you for fixing the codes!

I think relatively large man-hours needed for the remaining comments.
So, before fix the code, please tell us how you intend to fix the code and an estimate of the man-hours.

My comment itself may be inappropriate, so please do not hesitate to give me your comments.

2023-06-08 08:30 UTC, sanglevinh commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +      dispatch(reset())
@ReiHashimoto 
I changed the code to use AsyncThunk.
Can you help me check?
https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/131/files#diff-1dc02a1f3b3dea0f719c53d88a6c6a98a7a3df574097c6ed6ddf107a9e9d3828R96-R153

2023-06-08 08:39 UTC, sanglevinh commented
> @sanglevinh cc: @reactplus-thom Thank you for fixing the codes!
> 
> I think relatively large man-hours needed for the remaining comments. So, before fix the code, please tell us how you intend to fix the code and an estimate of the man-hours.
> 
> My comment itself may be inappropriate, so please do not hesitate to give me your comments.

@ReiHashimoto Thanks for your comment.
I finished fixing it. 
Can you check the parts I've corrected again?

2023-06-09 04:36 UTC, sanglevinh commented
> @sanglevinh Thanks, but getDataPipeLine looks complicated.
> 
> How about just passing other dispatch's results like following code?
> 
> https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/132/files
> 
> * Sorry, the code does not work because allowRun(using getDataPipeLine) added  while reviewing.

@ReiHashimoto Thanks
I will apply it.

2023-06-09 04:54 UTC, sanglevinh commented
> @sanglevinh Thanks, but getDataPipeLine looks complicated.
> 
> How about just passing other dispatch's results like following code?
> 
> https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/132/files
> 
> * Sorry, the code does not work because allowRun(using getDataPipeLine) added  while reviewing.

@ReiHashimoto  I edited and merged PR.
Thank you very much!

2023-06-12 02:27 UTC, ReiHashimoto commented
@itutu-tienday 
CC: @reactplus-thom 

- RUN, RUN_ALL実行前のワークフローで、ALIGNMENTノードの選択された画像の数がデータベースの画像数と一致しない問題を修正しました。
  - 原因
    - default workflowのimportの処理とsetSelectedFilePathの処理順が指定されていませんでした。
    - したがって、setSelectedFilePathの実行後にimportが実行される場合がありました。
    - その際にselectedFilePathがdefault_experiment.yamlのinput_0の内容で上書きされてしまうことで、selectedFilePathが一致しないという現象が起きていました。

[22080e8](https://github.com/arayabrain/MRIAnalysisStudioforMouse/pull/131/commits/22080e89c91df19f2e75487ede7a65b2e70c2d08)

2023-06-12 02:40 UTC, ReiHashimoto commented on frontend/src/store/slice/Pipeline/PipelineHook.ts
> +      dispatch(reset())
@sanglevinh 
Thank you, LGTM!

2023-06-12 02:41 UTC, ReiHashimoto approved these changes
LGTM

2023-06-12 05:49 UTC, merged