Workflow modification including new APIs
arayabrain/MRIAnalysisStudioforMouse pull request #139
Opened 2023-06-12 06:38 UTC by takada-naoki-github

- VBM test nodes and AnalysisInfo data class added.
- experiment.yaml update code modified.
- run_result and visualization mock APIs added.

2023-06-15 00:55 UTC, ReiHashimoto requested changes
一旦ロジックなどの確認の前に体裁を整えていただけますでしょうか

2023-06-15 01:05 UTC, ReiHashimoto commented on optinist/test_data/cjs/output/3a55fa37/experiment-original.yaml
test_data/cjsにif __name__ == "__main__"から呼び出すファイルが格納されていますが、
test_data/はpytestのテストコードで使用するデータのディレクトリです。
sample_dataなどに格納をお願いします。(あるいは、if __name__ = "__main__"での動作確認のコード削除をお願いしておりますので、不要であれば削除願います。)

2023-06-15 04:34 UTC, itutu-tienday commented
@takada-naoki-github 
以下、コメントいたします。

- 追加されているpipモジュールは、requirements.txt へ追記ください。
  - ※モジュールは、動作保証するバージョンを指定いただけるとよいと思います。
- MySQLへ直接接続する部分について、情報共有をお願いいたします。
  - バックエンド全体への影響範囲について（MySQLへ接続できない場合、BEの起動自体に影響がある？ 等）

2023-06-15 10:11 UTC, takada-naoki-github commented on .github/ISSUE_TEMPLATE/feature_request.md
ファイルを回復しました。

2023-06-15 10:11 UTC, takada-naoki-github commented on .github/workflows/test.yml
ファイルを回復いたしました。

2023-06-15 10:12 UTC, takada-naoki-github commented on .vscode/settings.json
ファイルを回復いたしました。

2023-06-15 10:12 UTC, takada-naoki-github commented on optinist/api/dataclass/analysis_info.py
> +    print(f'\nTest finished.')
動作確認用コードを削除しました。

2023-06-15 10:12 UTC, takada-naoki-github commented on optinist/api/rules/runner.py
> +    print(f'\nTest finished.')
動作確認用コードを削除しました。

2023-06-15 10:12 UTC, takada-naoki-github commented on optinist/wrappers/vbm_wrapper/alignment.py
> +    print(f'\nTest finished.')
動作確認用コードを削除しました。

2023-06-15 10:12 UTC, takada-naoki-github commented on optinist/wrappers/vbm_wrapper/nifti_image.py
> +    print(f'\nTest finished.')
動作確認用コードを削除しました。

2023-06-15 10:12 UTC, takada-naoki-github commented on optinist/wrappers/vbm_wrapper/vbm_test_initial.py
> +    print(f'\nTest finished.')
開発途中のもので、いったん削除しました。

2023-06-15 10:13 UTC, takada-naoki-github commented on optinist/wrappers/vbm_wrapper/vbm_test_processing.py
> +    print(f'\nTest finished.')
開発途中のもので、いったん削除しました。

2023-06-15 10:13 UTC, takada-naoki-github commented on optinist/wrappers/vbm_wrapper/vbm_visualization.py
> +    return image_file_paths
開発途中のもので、いったん削除しました。

2023-06-15 10:13 UTC, takada-naoki-github commented on optinist/test_data/cjs/output/3a55fa37/experiment-original.yaml
optinist/test_data/cjs のデータを削除しました。同様のデータを sample_data/cjs に置きました。

2023-06-16 02:23 UTC, ReiHashimoto requested changes

2023-06-16 02:23 UTC, ReiHashimoto commented on optinist/api/dataclass/analysis_info.py
> +        metadata['factors'] = factors_dict
ややネストが深く理解しにくいので、lambdaや内包表記など使用していただければと思います。

以下のような処理をされたいということであっていますか？
```
with open(filemap_path) as file:
    factors_info = json.load(file)

    metadata["factors"] = {
        factor_info["folder_name"]: {
            "file_path_list": list(
                map(lambda x: x["path"], factor_info.get("images", []))
            ),
            "within_factor": {
                sub_folder["folder_name"]: {
                    "file_path_list": list(
                        map(lambda x: x["path"], sub_folder.get("images", []))
                    )
                }
                for sub_folder in factor_info.get("sub_folders", [])
            },
        }
        for factor_info in factors_info
    }
```

2023-06-16 02:23 UTC, ReiHashimoto commented on optinist/routers/outputs.py
> +
使用されていないようですので、削除でお願いします

2023-06-16 02:23 UTC, ReiHashimoto commented on optinist/api/rules/runner.py
> +from optinist.api.dataclass.dataclass import AnalysisInfo, AnalysisStatus
AnalysisStatusはこのファイルで使用されていないので削除願います

2023-06-16 02:23 UTC, ReiHashimoto commented on optinist/routers/outputs.py
> +from optinist.wrappers.vbm_wrapper import vbm_visualization
削除された関数のため、エラーの原因になっています。
importを削除してください。

2023-06-16 02:23 UTC, ReiHashimoto commented on optinist/routers/run.py
> +import json
使用されていないようですので、削除してください。

2023-06-16 02:23 UTC, ReiHashimoto commented on optinist/routers/run.py
> +from optinist.api.experiment.experiment_reader import ExptConfigReader
こちらも使用されていませんので、削除してください。

2023-06-16 02:23 UTC, ReiHashimoto commented on optinist/wrappers/vbm_wrapper/alignment.py
> +        params_in: dict=None
念の為インデントを一つ下げていただけますか

2023-06-16 02:23 UTC, ReiHashimoto commented on optinist/wrappers/vbm_wrapper/alignment.py
> +            analysis_info_out.set_message(wf_input_path, error.args[0])
エラーハンドリングの処理が同一のようですが、RuntimeErrorを個別に指定されている理由はありますか？
なければExceptionだけで良いと思いますが。

2023-06-16 02:23 UTC, ReiHashimoto commented on optinist/wrappers/vbm_wrapper/nifti_image.py
> +import matplotlib.pyplot as plt
使用されていないようですので削除願います。

2023-06-16 02:23 UTC, ReiHashimoto commented on sample_data/cjs/1/filemap.json
> +		"sub-list": [{
sub_folders以外にsub_listというキーのパターンもある、という理解で良いですか？

2023-06-16 02:25 UTC, ReiHashimoto commented
@takada-naoki-github 
指摘事項追加いたしました。

また、全般に言えることなのですが、パスの指定方法について、
optinist.api.utils.filepath_createrのjoin_filepathを使用する方式を踏襲していただけますか？

相対表記などが混在していると予期せぬエラーの原因となります。

2023-06-16 03:01 UTC, takada-naoki-github commented on optinist/routers/outputs.py
> +
削除しました。

2023-06-16 03:01 UTC, takada-naoki-github commented on optinist/api/rules/runner.py
> +from optinist.api.dataclass.dataclass import AnalysisInfo, AnalysisStatus
削除しました。

2023-06-16 03:17 UTC, takada-naoki-github commented on optinist/routers/outputs.py
> +from optinist.wrappers.vbm_wrapper import vbm_visualization
削除しました。

2023-06-16 03:17 UTC, takada-naoki-github commented on optinist/routers/run.py
> +import json
削除しました。

2023-06-16 03:18 UTC, takada-naoki-github commented on optinist/routers/run.py
> +from optinist.api.experiment.experiment_reader import ExptConfigReader
削除しました。

2023-06-16 03:24 UTC, takada-naoki-github commented on optinist/wrappers/vbm_wrapper/alignment.py
> +            analysis_info_out.set_message(wf_input_path, error.args[0])
エラー処理のほうはまだ固まっていないので、Exception だけに変更しました。

2023-06-16 03:27 UTC, ReiHashimoto commented on optinist/wrappers/vbm_wrapper/alignment.py
> +        params_in: dict=None
失礼しました、こちらの表現が誤っていました。
インデントを減らす意図でした。

当方にて修正いたしました。

2023-06-16 04:17 UTC, ReiHashimoto commented on sample_data/cjs/1/filemap.json
> +		"sub-list": [{
sub-listは存在しない想定(松枝様より)

sample_dataもsub_foldersに統合でお願いします。

2023-06-20 03:17 UTC, itutu-tienday approved these changes

2023-06-20 03:21 UTC, ReiHashimoto approved these changes
残課題はありますが、現時点で一旦マージします

2023-06-20 03:27 UTC, merged